// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQy-F-k32TFD-cL14vKatD2UqfLQA89Jo',
    appId: '1:216680883540:web:40680f296ab492f17a54c1',
    messagingSenderId: '216680883540',
    projectId: 'staycay-owner',
    authDomain: 'staycay-owner.firebaseapp.com',
    storageBucket: 'staycay-owner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDES8dMXJFQxWKZkT7ZyyWdTBrLrErvNW4',
    appId: '1:216680883540:android:691d8949948b9e157a54c1',
    messagingSenderId: '216680883540',
    projectId: 'staycay-owner',
    storageBucket: 'staycay-owner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWHBUXv6g3I3Rad3XBIwTjkUK4-akilEI',
    appId: '1:216680883540:ios:04b11e8fd91452177a54c1',
    messagingSenderId: '216680883540',
    projectId: 'staycay-owner',
    storageBucket: 'staycay-owner.firebasestorage.app',
    iosBundleId: 'com.example.heavenrockRegistry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWHBUXv6g3I3Rad3XBIwTjkUK4-akilEI',
    appId: '1:216680883540:ios:04b11e8fd91452177a54c1',
    messagingSenderId: '216680883540',
    projectId: 'staycay-owner',
    storageBucket: 'staycay-owner.firebasestorage.app',
    iosBundleId: 'com.example.heavenrockRegistry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQy-F-k32TFD-cL14vKatD2UqfLQA89Jo',
    appId: '1:216680883540:web:3681d1a6c7974ce37a54c1',
    messagingSenderId: '216680883540',
    projectId: 'staycay-owner',
    authDomain: 'staycay-owner.firebaseapp.com',
    storageBucket: 'staycay-owner.firebasestorage.app',
  );
}
